version: '3'
services:
  web:
    build: .
    command: npm run server:watch
    depends_on:
      - postgres
    volumes: 
      - .:/app/
      - /app/node_modules
    network_mode: service:postgres
    environment: 
      - DATABASE_URL=postgres://bbayard:potato@db:5432/dinosaur_development
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
      - "3001:3001"
    environment:
      POSTGRES_USER: bbayard
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: dinosaur_development
