version: '3'
services:
  web_test:
    build: .
    depends_on:
      - postgres_test
    volumes: 
      - .:/app/
      - /app/node_modules
    network_mode: service:postgres_test
    environment: 
      DATABASE_URL: postgres://bbayard:potato@db:5432/dinosaur_test
      NODE_ENV: test
  postgres_test:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
      - "3001:3001"
    environment:
      POSTGRES_USER: bbayard
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: dinosaur_test
      DATABASE_URL: postgres://bbayard:potato@db:5432/dinosaur_test
